name: join-calendar

on:
  push:
    branches: main
  schedule:
  - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: install requirements
      run: |
        pip install -r scripts/calendar/requirements.txt
    
    - name: run script
      run: |
        python scripts/calendar/ics_join.py

    - name: commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update calendar"
        git push
