name: resume-pdf-render

on:
  push:
    branches: main
    paths:
      - '.github/workflows/resume.yml'
      - 'resume.md'

jobs:
  render:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2

      - name: Install Deps
        run: sudo apt install pandoc

      - name: Render PDF
        run: pandoc -s -V geometry:margin=0.5in -o alex_cluff_resume.pdf resume.md

    # - name: Commit PDF
    #   run: |
    #     git config --local user.email "github-actions@no-reply.github.com"
    #     git config --local user.name "github-actions[bot]"
    #     git add alex_cluff_resume.pdf
    #     git commit -m "Render PDF"
    #     git push
