name: user-statistician

on:
  push:
    branches: main
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      with:
        colors: dark-dimmed
        custom-title: My GitHub Statistics
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}